id: I09D5D8B4
default_language: zh
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-08 15:13:26.680011
last_modified: 2023-02-08 15:13:26.680123
source_metadata:
  title: Mañjuśrīvikrīḍitasūtra
  language: zh
bases:
  CC79:
    base_file: CC79.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
